### PR TITLE
Fix Sonarcloud warnings for bugs

### PR DESCRIPTION
**Pull request by tsolakoua**
- Fix ArrayList Init
- Replace == with .equals for String comparison

### CODE REVIEW

**Comment by steve-donovan** [comment]
I think some of your constants would be better as enums to prevent this exact issue going forward. imho

**Comment by tsolakoua** [comment]
@steve-donovan thanks for your feedback! Do you think it would be better to make the updates in this PR or in the future? Any particular variables that you think make sense to be as enums?

**Comment by steve-donovan** [comment]
Hi @tsolakoua 
are you guys duplicating the verbs etc because you only want to expose a subset of those from HttpMethod and RequestMethod ? If not, then I don't understand the need to duplicate the standard JDK definitions. Otherwise, I think you should follow the RequestMethod enum and define your subsets. The problem with String constants is that people can try any invented values for evaluation and won't get errors until runtime. There are other advantages. 
As to whether you do in this or another PR - I'm just a consumer of your API who is happy to help 😊 If you need a hand, pleasee let me know, I'd be happy to help out.

**Comment by steve-donovan** [comment]
You'd need to feed it all the way down to this guy and make relevant changes (you gain type safety all the way down): 
Screenshot 2022-09-07 at 17 17 22

**Comment by steve-donovan** [comment]
if it helps or just delete

https://github.com/amadeus4dev/amadeus-java/pull/208

**Comment by tsolakoua** [comment]
@steve-donovan Thanks for the explanation, it's clear now :) Your changes at #208 are very useful for the verbs! Will merge this particular PR and work on the other variables in future PRs.

**Comment by steve-donovan** [comment]
> @steve-donovan Thanks for the explanation, it's clear now :) Your changes at #208 are very useful for the verbs! Will merge this particular PR and work on the other variables in future PRs.

maybe create a new constants package for these changes 🤷‍♂️

**Review by gustavo-bertoldi — APPROVED** [review]

**Pull request merged**
