### PR TITLE
Make delays in DatedFlight.Timing accept an array

### LINKED ISSUE #178: Unexpected JSON response
## Description

The SDK throws an JSON parse exception when using `com.amadeus.schedule.Flights#get(com.amadeus.Params)`.

[`com.amadeus.resources.DatedFlight.Timing#delays`](https://github.com/amadeus4dev/amadeus-java/blob/master/src/main/java/com/amadeus/resources/DatedFlight.java#L69) is now
```java
private @Getter Delay delays;
```

but should be
```java
private @Getter Delay[] delays;
```

## Steps to Reproduce

Use `com.amadeus.schedule.Flights#get(com.amadeus.Params)` with a delayed flight, for example:

```kotlin
// Make sure this flight is delayed when testing
val carrierCode = "VY"
val flightNumber = "8436"
val departureDate = "2022-07-06" // Take a date in the future

val params = Params.with("carrierCode", carrierCode)
            .and("flightNumber", flightNumber)
            .and("scheduledDepartureDate", departureDate)

val flights = client.schedule.flights.get(params)
```

It will throw this exception:
```kotlin
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $[0].flightPoints[0].departure.timings[0].delays
    at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
    at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.Gson.fromJson(Gson.java:991)
    at com.google.gson.Gson.fromJson(Gson.java:1062)
...
```

While this is the JSON response from the API
```json
[
    {
        "type": "DatedFlight",
        "scheduledDepartureDate": "2022-07-06",
        "flightDesignator": {
            "carrierCode": "VY",
            "flightNumber": 8436
        },
        "flightPoints": [
            {
                "iataCode": "LIS",
                "departure": {
                    "terminal": {
                        "code": "1"
                    },
                    "timings": [
                        {
                            "qualifier": "STD",
                            "value": "2022-07-06T17:25+01:00",
                            "delays": [
                                {
                                    "duration": "PT22M"
                                }
                            ]
                        }
                    ]
                }
            },
            {
                "iataCode": "AMS",
                "arrival": {
                    "timings": [
                        {
                            "qualifier": "STA",
                            "value": "2022-07-06T21:25+02:00"
                        }
                    ]
                }
            }
        ],
        "segments": [
            {
                "boardPointIataCode": "LIS",
                "offPointIataCode": "AMS",
                "scheduledSegmentDuration": "PT3H",
                "partnership": {
                    "operatingFlight": {
                        "carrierCode": "IB",
                        "flightNumber": 5857
                    }
                }
            }
        ],
        "legs": [
            {
                "boardPointIataCode": "LIS",
                "offPointIataCode": "AMS",
                "aircraftEquipment": {
                    "aircraftType": "320"
                },
                "scheduledLegDuration": "PT3H"
            }
        ]
    }
]
```

__Expected Behavior:__ The SDK can parse the json sent by the API for a delayed flight

__Actual Behavior:__ The SDK throws an exception. It looks like the API is returning an array where an object is expected or the SDK should expect an array where it is now expecting an object.

__Stable Behavior?__ For __non-delayed flights__ 0%, for __delayed flights__ 100%

## Versions

JVM 17
SDK `com.amadeus:amadeus-java:6.1.0`

## Checklist

Please make sure you checked the following:

* Did you download the latest version of this library?
Yes

### PR DESCRIPTION
**Pull request by frankkoornstra**
Delays is an array of Delay, not an object.

Fixes #178

## Checklist

Tests are all :heavy_check_mark:

### CODE REVIEW

**Comment by jabrena** [comment]
Hi @frankkoornstra, It is necessary to upload the tests in the PR.
Any PR is an atomic operation for a new consistent state in the library.

**Comment by frankkoornstra** [comment]
@jabrena can this be merged, please? This isn't a minor bug, it's making the whole flight lookup feature unusable with the many delays we have in the past period.

**Comment by jabrena** [comment]
Hi mate, tomorrow, I will work on it. :)

**Comment by jabrena** [comment]
Hi @frankkoornstra, 

First, apologies by the delay because you were right with this PR. I was checking the portal and our OAS files and yes, Timing objects returns an array of Delays.

OAS Evidence:
https://github.com/amadeus4dev/amadeus-open-api-specification/blob/main/spec/json/OnDemandFlightStatus_v2_swagger_specification.json

Portal Evidence:
https://developers.amadeus.com/self-service/category/air/api-doc/on-demand-flight-status/api-reference

image

**Comment by frankkoornstra** [comment]
Nice, thanks! When do you think a new version will be released with this patch included?

**Comment by tsolakoua** [comment]
Hello @frankkoornstra , you can now install and use the version `6.2.0`

**Pull request merged**
