### PR TITLE
Update Traveler resource model

### LINKED ISSUE #196: com.amadeus.resources.Traveler has inconsistencies between constructors
## Description

1. **Traveler** constructor only sets a subset of the class members even though all are provided in the method signature.
```
  public Traveler(String id, String dateOfBirth, String gender,
      Name name, Contact contact, Document[] documents) {
    this.name = name;
    this.contact = contact;
  }
```

2. **Traveler.Contact** parameterized constructor has no body
```
    public Contact(Phone phones, String emailAddress) {
    }
```

3. **Traveler.Document** parameterized constructor has no body
```
    public Document(String documentType, String number, String expiryDate, 
        String issuanceCountry, String nationality, boolean holder) {

    }
```

4. **Traveler.Phone** parameterized constructor has no body
```
    public Phone(String countryCallingCode, String number) {
    }
```

Should I add appropriate bodies, drop the parameterized constructors completely and rely on setter usage? What are the mandatory fields, and how to enforce them if only using setters -rely purely on marshaling?

Let me know and I'll raise a PR.

### PR DESCRIPTION
**Pull request by tsolakoua**
Fixes #196

### CODE REVIEW

**Review by steve-donovan — COMMENTED** [review]
Hi 
I understand this is still a WIP, but just wanted to highlight that FlightOrders.post variants, take Traveler as arg, and return a FlightOrder. It doesn't feel very clean to instantiate a FlightOrder to simply wrap a Traveler for the post call when you're getting a FlightOrder in response. Hope that makes some kind of sense.

**Comment by tsolakoua** [comment]
Hello @steve-donovan! 

We discussed internally and we thought to remove the Traveler resource, since its a duplicate class and keep it only in the FlightOrders resource file. Could you explain in more detail what the issue would be if we follow this approach? And what solution would you think is a better one? Thanks again for your feedback and contributions very much, it's much appreciated :)

**Comment by steve-donovan** [comment]
Hi @tsolakoua - I think it's looking good; I noticed you've already converted the inner classes to statics.

**Comment by steve-donovan** [comment]
in general, I think maybe you should be using interfaces more, to give you a layer of abstraction so it's easier to make non-breaking changes in the future ie separate the API contract and your underlying implementation.

sorry - it's nothing to do with this PR - just an observation

**Comment by tsolakoua** [comment]
@jabrena @minjikarin please review

**Comment by jabrena** [comment]
Hi @tsolakoua, fine with the changes. 
Go ahead

**Pull request merged**
